/* 한국어 UI 문자열 */
var STR = {
  appName: '티츄',
  subtitle: '4인 파트너 카드게임',
  nickname: '닉네임',
  createRoom: '+ 새 방 만들기',
  joinRoom: '방 참여',
  roomCode: '방 코드',
  solo: '혼자 연습 (봇 3명)',
  soloResume: '연습 게임 이어하기',
  start: '게임 시작',
  waitingHost: '방장이 시작하면 게임이 열립니다',
  teamHint: '마주 보는 자리끼리 한 팀입니다',
  sit: '앉기',
  empty: '비어있음',
  addBot: '+ 봇',
  removeBot: '봇 제거',
  kick: '강퇴',
  leave: '나가기',
  copyLink: '초대 링크 복사',
  copied: '복사됐습니다',
  you: '나',
  bot: '봇',
  host: '방장',
  myTeam: '우리',
  oppTeam: '상대',
  round: '라운드',
  grandTitle: '라지 티츄를 선언할까요?',
  grandDesc: '처음 8장만 보고 결정합니다. 1등 완주 시 +200, 실패 시 -200',
  grandCall: '라지 티츄!',
  grandPass: '선언 안 함',
  tichuBtn: '스몰 티츄',
  tichuConfirm: '정말? 스몰 티츄! (±100)',
  tichuBadge: '스몰',
  grandBadge: '라지',
  rulesBtn: '📖 규칙 보기',
  rulesBtnPlain: '규칙 보기',
  firstTimeHint: '처음이라면 「선언 안 함」을 누르세요',
  leaveConfirm: '정말 나가시겠어요?\n게임 중이면 빈자리는 봇이 이어받습니다.\n(방 목록에서 「이어받기」로 다시 돌아올 수 있어요)',
  wishCancel: '취소 — 카드 다시',
  targetScore: '목표 점수',
  historyBtn: '점수 기록',
  historyTitle: '라운드별 점수',
  noHistory: '아직 끝난 라운드가 없습니다',
  toBot: '봇으로 교체',
  confirmHint: '한 번 더 누르면 확정',
  chat: '채팅',
  chatSend: '전송',
  chatPlaceholder: '메시지 입력…',
  chatEmpty: '첫 메시지를 보내보세요',
  botLevelLbl: '봇 단수',
  botDevil: '악마',
  botThinking: '생각 중…',
  statsBtn: '📊 전적',
  statsTitle: '전적',
  botDan1: '1단',
  toLobby: '대기실로',
  teamsLbl: '팀 배정',
  teamsOrder: '들어온 순서',
  teamsRandom: '랜덤',
  teamsShuffled: '팀을 무작위로 섞었습니다',
  teamsOrdered: '들어온 순서대로 앉혔습니다',
  teamsHint: '마주 보는 자리가 한 팀 — 순서대로 앉히거나 무작위로 섞습니다 (방장만)',
  botDan2: '2단',
  botDan3: '3단',
  botDan4: '4단',
  cancel: '취소',
  spectate: '관전하기',
  spectating: '관전 중',
  spectateHint: '관전자는 카드를 낼 수 없고 손패도 보이지 않습니다. 채팅과 빈자리 착석은 가능합니다.',
  spectators: '관전',
  sitDown: '이 자리에 앉기',
  spectateJoin: '자리가 없어 관전으로 입장했습니다',
  rerollBtn: '패 다시 받기',
  rerollConfirm: '팀 전체가 패를 다시 받을까요?',
  rerollDesc: '네 사람 모두 새 패를 받습니다. 우리 팀 점수에서 <b>75점</b>이 차감되고, 라지 티츄 선언과 교환도 처음부터 다시 합니다.',
  rerollNeedMate: '파트너도 눌러야 실행됩니다 — 팀 합의가 필요한 선택입니다.',
  rerollWaiting: '파트너 동의 대기 중…',
  rerollMateWants: '파트너가 패 다시 받기를 원합니다',
  rerollLeft: '팀 잔여',
  rerollBy: '님 팀이 패를 다시 받았습니다',
  botHintDan1: '1단 · 자가대전 약 1,700판 학습 (혼자 연습은 첫 시작 때 잠깐 준비)',
  botHintDan2: '2단 · 1단 실력 + 교환 개선(마작·개 보유로 1·2등 완주). 1단을 점수차 66%로 앞섬',
  botHintDan3: '3단 · RL 자가대전 가중치 + 손패별 학습 교환. 2단을 점수차 54%로 앞섬(1,920판 검증)',
  botHintDan4: '4단 · 3단과 같은 정책이지만 한 수를 4배 오래 읽는다. 뻔한 수는 즉답하고 어려운 수에 시간을 몰아쓴다(2,880판 검증)',
  botHintDevil: '악마: 상대 패를 보고 둡니다 — 등급 밖 치트 (혼자 연습 전용)',
  botHintDanNext: '더 강한 봇이 직전 단을 점수차 기준으로 이기면 다음 단이 열립니다',
  botOnlineNote: '고수·악마는 「혼자 연습」에서만',
  roomListTitle: '열린 방',
  roomListEmpty: '아직 열린 방이 없습니다 — 첫 방을 만들어보세요',
  inGameCount: '게임중',
  rejoinChip: '이어받기 ›',
  ghostBtn: '투명도',
  exchangeTitle: '카드 교환 — 각 사람에게 1장씩',
  exchangeConfirm: '교환 확정',
  exchangeWaiting: '다른 참가자의 교환을 기다리는 중…',
  received: '받은 카드',
  play: '내기',
  pass: '패스',
  bombHint: '폭탄 끼어들기 가능!',
  wishTitle: '소원 숫자를 선언하세요 (1을 냈습니다)',
  wishDesc: '다른 사람은 낼 수 있으면 반드시 이 숫자를 내야 합니다. 안 해도 됩니다.',
  wishNone: '소원 없이 내기',
  wishChip: '소원',
  dragonTitle: '용으로 가져온 카드, 어느 상대에게 줄까요?',
  pilePts: '점',
  yourTurn: '내 차례',
  leadFree: '아무 조합이나 낼 수 있습니다',
  out: '완주',
  disconnected: '연결 끊김',
  botActsIn: '초 후 봇이 대신 진행',
  roundEndTitle: '라운드 결과',
  oneTwo: '원투 피니시! +200',
  cardPts: '카드 점수',
  bonus: '선언',
  total: '합계',
  nextRound: '다음 라운드',
  newGame: '새 게임',
  winA: '승리!',
  hostWillContinue: '방장이 다음 라운드를 시작합니다…',
  gameOverTitle: '게임 종료',
  connecting: '연결 중…',
  reconnecting: '재연결 중…',
  connected: '연결됨',
  offline: '오프라인',
  replaced: '다른 탭/기기에서 접속했습니다. 이 화면은 멈춥니다.',
  roomClosed: '방이 닫혔습니다',
  kicked: '강퇴되었습니다',
  refreshNew: '새 버전이 있습니다 — 새로고침 해주세요',
  help: '도움말',
  passChip: '패스',
  finishRank: ['1등', '2등', '3등', '4등']
};
